Repository microsoft/bedrock, pull requests merged in 2019-05, with the labels that each got.

#386 Resolved issues with ImageTagRelease.md
  gitops/azure-devops/ImageTagRelease.md
  gitops/azure-devops/images/create-release.png
  gitops/azure-devops/images/release-task1.png
  gitops/azure-devops/images/release-task2.png
  gitops/azure-devops/images/releases-add-final-stage.png
  gitops/azure-devops/images/releases-agent-pool.png
  gitops/azure-devops/images/releases-clone-stages.png
  gitops/azure-devops/images/releases-clone.png
  gitops/azure-devops/images/releases-empty-job.png
Labels: documentation, services-team

#385 Add content for Octopus Deploy
  gitops/octopus/OctopusDeploy.md
  gitops/octopus/images/add-deployment-target.png
  gitops/octopus/images/create-octopus-deploy-2.png
  gitops/octopus/images/create-octopus-deploy-3.png
  gitops/octopus/images/create-octopus-deploy.png
  gitops/octopus/images/gitops-octopus-deploy.png
  gitops/octopus/images/octo-choose-env-role.png
  gitops/octopus/images/octo-create-account.png
  gitops/octopus/images/octo-deploy-target-communication.png
  gitops/octopus/images/octo-deploy-target-health1.png
  gitops/octopus/images/octo-deploy-target-health2.png
  gitops/octopus/images/octo-env-variables.png
  gitops/octopus/images/octo-release-logs.png
  gitops/octopus/images/octo-release1.png
  gitops/octopus/images/octo-release2.png
  gitops/octopus/images/octo-release3.png
  gitops/octopus/images/octo-release4.png
  gitops/octopus/images/octo-successful-deploy.png
  gitops/octopus/images/octopus-add-account.png
  gitops/octopus/images/octopus-create-env.png
  gitops/octopus/images/octopus-deploy-resources.png
  gitops/octopus/images/octopus-public-ip.png
  gitops/octopus/images/ssh-connection.png
Labels: documentation, services-team

#400 Fixes to build and release scripts
  gitops/azure-devops/build.sh
  gitops/azure-devops/release.sh
Labels: services-team

#392 Decoupled integration test to separate tasks in CI
  azure-pipelines.yml
Labels: infra-team, tests

#407 Adding githook linting script for code formatting
  cluster/azure/aks-gitops/main.tf
  cluster/azure/aks-gitops/variables.tf
  cluster/azure/aks/kubeconfig.tf
  cluster/azure/aks/main.tf
  cluster/azure/aks/outputs.tf
  cluster/azure/aks/virtualnodeaddon.tf
  cluster/azure/backend-state/locals.tf
  cluster/azure/backend-state/main.tf
  cluster/azure/backend-state/storage-account.tf
  cluster/azure/keyvault/main.tf
  cluster/azure/keyvault/output.tf
  cluster/azure/keyvault/variables.tf
  cluster/azure/keyvault_flexvol/main.tf
  cluster/azure/keyvault_flexvol/variables.tf
  cluster/azure/keyvault_flexvol_role/main.tf
  cluster/azure/keyvault_flexvol_role/variables.tf
  cluster/azure/keyvault_policy/main.tf
  cluster/azure/keyvault_policy/outputs.tf
  cluster/azure/keyvault_policy/variables.tf
  cluster/azure/keyvault_secret/main.tf
  cluster/azure/keyvault_secret/outputs.tf
  cluster/azure/keyvault_secret/variables.tf
  cluster/azure/provider/main.tf
  cluster/azure/tm-endpoint-ip/main.tf
  cluster/azure/tm-profile/variables.tf
  cluster/azure/vnet/main.tf
  cluster/azure/vnet/output.tf
  cluster/azure/vnet/variables.tf
  cluster/common/kubediff/main.tf
  cluster/common/kubediff/variables.tf
  cluster/environments/azure-multiple-clusters/aks-centralus-variables.tf
  cluster/environments/azure-multiple-clusters/aks-centralus.tf
  cluster/environments/azure-multiple-clusters/aks-eastus-variables.tf
  cluster/environments/azure-multiple-clusters/aks-eastus.tf
  cluster/environments/azure-multiple-clusters/aks-variables.tf
  cluster/environments/azure-multiple-clusters/aks-westus-variables.tf
  cluster/environments/azure-multiple-clusters/aks-westus.tf
  cluster/environments/azure-multiple-clusters/main.tf
  cluster/environments/azure-multiple-clusters/outputs.tf
  cluster/environments/azure-multiple-clusters/trafficmanager-variables.tf
  cluster/environments/azure-simple/variables.tf
  cluster/environments/azure-single-keyvault/main.tf
  cluster/environments/azure-single-keyvault/variables.tf
  test/README.md
  test/bedrock_Azure_common_kv_test.go
  test/bedrock_Azure_mc_test.go
  test/bedrock_Azure_simple_test.go
Labels: infra-team, tests

#395 Add content for TeamCity
  gitops/azure-devops/build.sh
  gitops/teamcity/ImageTagRelease.md
  gitops/teamcity/ManifestGeneration.md
  gitops/teamcity/README.md
  gitops/teamcity/build.sh
  gitops/teamcity/images/acr-diagram.png
  gitops/teamcity/images/acr_published_done.png
  gitops/teamcity/images/build_complete.png
  gitops/teamcity/images/build_name.png
  gitops/teamcity/images/configure_basic_settings.png
  gitops/teamcity/images/create_admin_account.png
  gitops/teamcity/images/create_project.png
  gitops/teamcity/images/create_project_app_code.png
  gitops/teamcity/images/create_project_from_catalyst_code.png
  gitops/teamcity/images/deployment_inprogress.png
  gitops/teamcity/images/docker_api_create_configs.png
  gitops/teamcity/images/env_variables_acr.png
  gitops/teamcity/images/from_repository.png
  gitops/teamcity/images/gitops-diagram.png
  gitops/teamcity/images/mysql_settings.png
  gitops/teamcity/images/output_available.png
  gitops/teamcity/images/parameters_find.png
  gitops/teamcity/images/password_variable.png
  gitops/teamcity/images/search_marketplace.png
  gitops/teamcity/images/summary.png
  gitops/teamcity/images/transform_and_publish_step.png
  gitops/teamcity/images/use_none.png
  gitops/teamcity/images/variables.png
  gitops/teamcity/images/virtual_machine_settings.png
Labels: documentation, services-team

#419 Update docs for TeamCity
  gitops/README.md
  gitops/azure-devops/build.sh
  gitops/teamcity/ImageTagRelease.md
  gitops/teamcity/images/env_variables_acr.png
Labels: developer experience, documentation, services-team

#409 Add content around Image Tag Release for Octopus Deploy
  gitops/octopus/ImageTagRelease.md
  gitops/octopus/README.md
  gitops/octopus/images/image-tag-release-pipeline.png
  gitops/octopus/images/octo-add-another-step.png
  gitops/octopus/images/octo-add-script.png
  gitops/octopus/images/octo-add-step.png
  gitops/octopus/images/octo-create-new-proj-2.png
  gitops/octopus/images/octo-create-new-proj.png
  gitops/octopus/images/octo-create-release.png
  gitops/octopus/images/octo-define-process.png
  gitops/octopus/images/octo-dep-targets-qa.png
  gitops/octopus/images/octo-deploy-to-qa.png
  gitops/octopus/images/octo-deploy.png
  gitops/octopus/images/octo-deploying.png
  gitops/octopus/images/octo-download-scripts-2.png
  gitops/octopus/images/octo-download-scripts.png
  gitops/octopus/images/octo-enable-features.png
  gitops/octopus/images/octo-process-script.png
  gitops/octopus/images/octo-qa-deploy.png
  gitops/octopus/images/octo-release-notes.png
  gitops/octopus/images/octo-release-snapshot.png
  gitops/octopus/images/octo-release-variables.png
  gitops/octopus/images/octo-run-release-inline.png
  gitops/octopus/images/octo-run-release-step.png
  gitops/octopus/images/octo-save.png
  gitops/octopus/images/octo-task-logs.png
Labels: documentation, services-team

#421 Resolved a few bugs in the Octopus Deploy documentation
  gitops/octopus/OctopusDeploy.md
  gitops/octopus/images/octo-deploy-target-communication.png
  gitops/octopus/images/octo-env-variables.png
  gitops/octopus/images/octopus-add-account.png
  gitops/octopus/images/octopus-create-account.png
Labels: documentation, services-team

#422 Docs for TeamCity triggering Octopus Deploy
  gitops/teamcity/ConnectToOctopus.md
  gitops/teamcity/ImageTagRelease.md
  gitops/teamcity/README.md
  gitops/teamcity/images/git_hash_step.png
  gitops/teamcity/images/trigger_octo_build_step.png
  gitops/teamcity/images/trigger_octo_logs.png
Labels: documentation, services-team

#426 Updated the Image Tage Release Pipeline doc for Octopus to include triggering steps
  gitops/octopus/ImageTagRelease.md
  gitops/octopus/README.md
  gitops/octopus/images/octo-hld-manifest.png
  gitops/octopus/images/octo-release-variables.png
Labels: documentation, services-team

#431 Added documentation around Automatic Release Creation, auto-deploy, and NuGet packages
  gitops/octopus/ImageTagRelease.md
  gitops/octopus/images/octo-acr-setup-2.png
  gitops/octopus/images/octo-acr-setup.png
  gitops/octopus/images/octo-add-lifecycle.png
  gitops/octopus/images/octo-add-phase.png
  gitops/octopus/images/octo-deploy-package.png
  gitops/octopus/images/octo-deploy-release-config.png
  gitops/octopus/images/octo-deploy-release-step.png
  gitops/octopus/images/octo-final-lifecycle.png
  gitops/octopus/images/octo-lifecycle-add-env.png
  gitops/octopus/images/octo-new-process.png
  gitops/octopus/images/octo-nuget-package.png
  gitops/octopus/images/octo-release-variables.png
  gitops/octopus/images/octo-reorder-steps.png
  gitops/octopus/images/octo-select-package.png
Labels: documentation, services-team

#432 TeamCity: Add NuGet package steps to trigger Octopus Deploy
  gitops/teamcity/ConnectToOctopus.md
  gitops/teamcity/images/nuget_logs.png
  gitops/teamcity/images/nuget_step.png
  gitops/teamcity/images/trigger_octo_logs.png
Labels: documentation, services-team

#448 Added documentation for azure-common-infra and azure-single-keyvault
  cluster/azure/README-maintenance.md
  cluster/environments/azure-common-infra/README.md
  cluster/environments/azure-single-keyvault/README.md
Labels: documentation, infra-team
