Repository microsoft/bedrock, pull requests merged in 2019-06, with the labels that each got.

#451 Jenkins documentation with manual build steps
  gitops/README.md
  gitops/jenkins/ManifestGeneration.md
  gitops/jenkins/README.md
  gitops/jenkins/images/build_step.png
  gitops/jenkins/images/build_triggers.png
  gitops/jenkins/images/build_with_parameters.png
  gitops/jenkins/images/console_output.png
  gitops/jenkins/images/copy_jenkins_url.png
  gitops/jenkins/images/freestyle_project.png
  gitops/jenkins/images/jenkins_basic_settings.png
  gitops/jenkins/images/jenkins_step_2.png
  gitops/jenkins/images/jenkins_step_3.png
  gitops/jenkins/images/jenkins_step_4.png
  gitops/jenkins/images/outputs_tab.png
  gitops/jenkins/images/parameters.png
  gitops/jenkins/images/source_code_management.png
  gitops/jenkins/images/ssh_jenkins_blue_page.png
  gitops/jenkins/images/test_from_jenkins.png
  gitops/jenkins/images/unlock_jenkins.png
  gitops/jenkins/images/view_builds.png
  gitops/jenkins/images/visudo.png
Labels: developer experience, documentation

#462 Fix bug in GitOps build script for custom HLD repo
  gitops/azure-devops/build.sh
Labels: bug, services-team

#464 Updated README for Rings
  gitops/rings/README.md
Labels: documentation
