Repository microsoft/bedrock, pull requests merged in 2019-04, with the labels that each got.

#308 Update images for AzDO Pipeline Releases documentation
  gitops/azure-devops/images/artifact-build.png
  gitops/azure-devops/images/deployment-approvals.png
  gitops/azure-devops/images/release-task1.png
  gitops/azure-devops/images/release-task2.png
  gitops/azure-devops/images/releases-continuous-dep.png
  gitops/azure-devops/images/releases-env.png
  gitops/azure-devops/images/releases-pipeline-var.png
Labels: documentation, services-team

#346 Test GitOps pipeline as part of CI
  azure-pipelines.yml
  gitops/azure-devops/README.md
  gitops/azure-devops/build.sh
Labels: services-team, tests

#367 Plumb through enable_flux to aks-gitops interface
  cluster/azure/aks-gitops/main.tf
  cluster/azure/aks-gitops/variables.tf
Labels: infra-team
